### ISSUE TITLE
error while loading shared libraries: libavformat.so.59: cannot open shared object file: No such file

### ISSUE THREAD

**Issue by 9acca9** [JuanKman94/readymedia-transcode#2]
HI.
I update the system and now im getting this error when trying to run minidlna.
What can i do?
Thanks!

**Comment by 9acca9** [comment]
https://forum.manjaro.org/t/readymedia-transcode-minidlna-libavformat-so-59-cannot-open-file/142916

**Comment by JuanKman94** [comment]
Hey, sorry for the late response. Yeah, if you upgraded libavformat and a breaking change was introduced your best bet would be to recompile and see which part of the code broke.

Having said that, I'm not an expert on this codebase. I'm glad you got a clear response from the manjaro forum!
